### ISSUE TITLE
Enforce (or not) slide at the first cell

### ISSUE THREAD

**Issue by damianavila** [damianavila/live_reveal#29]
From #26:

I'm running into issues with trying to "skip" cells in slideshows with live_reveal. First, if you try to skip the very first fragment (e.g. if it contains import statements, etc.), the cell is not skipped, and the state of the cell is switched to "slide" from "skip" automatically.
This is a design decision because a lot of people could forget to setup the first cell to show as an slide... but you are right about some uses cases where is good to hide the first (or more) cells... I think I have to re-evaluate this decision or come up with a better solution...

**Comment by damianavila** [comment]
Just to give an update, I still think the same about this, targeting to 3.x compatibility.

**Comment by takluyver** [comment]
FWIW, I just ran into this and had a WTF moment - I wanted some imports at the top of the notebook so I'd remember to run them before going into presentation mode, but they would be hidden in presentation mode.

Though I can also see that it would be surprising if you went into slide mode and were missing content unexpectedly.

Perhaps automatically make the first cell 'slide' if it doesn't have a slide type set, but if the user sets the slide type to 'skip', assume they mean it.

**Comment by damianavila** [comment]
>Perhaps automatically make the first cell 'slide' if it doesn't have a slide type set, but if the user sets the slide type to 'skip', assume they mean it.

Seems a good compromise...
