### ISSUE TITLE
Adding a new cell below the last cell in a slide causes blank slide show

### ISSUE THREAD

**Issue by fonnesbeck** [damianavila/live_reveal#31]
When attempting to create a cell to demonstrate code in a live slideshow, adding a cell below the last cell on the slide (via command-b) causes the slide to go blank. Subsequent forward or backward movement from one slide to the other also produces blank slides, and the only way to recover is to close the slideshow completely and restart it. 

Creating a cell *above* an existing cell, or below a cell that is not the last cell does not cause this to happen.

**Comment by damianavila** [comment]
As I said... inserting cells is not viable with this extension now... and make viable probably takes a lot of time and effort... so, closing for now... if someone have ideas or want to discuss further we can reopen it again. Thanks.
