### ISSUE TITLE
Install for IRuby

### ISSUE THREAD

**Issue by jjconti** [damianavila/live_reveal#41]
To make live_reveal work for IRuby, after install do:

~/.config/iruby$ cp -fr ../../.ipython/nbextensions/livereveal/ nbextensions/

This is because IRuby config files are placed in .config/iruby.

**Comment by damianavila** [comment]
With IPython/Jupyter 3.0 the nbextensions folder has to be available to all the kernel using the kernel architecture (probably the first ones are not using the new architecture, I don't know the state of the ruby kernel).
I will close this one... if somebody needs the reference, it is available here despite of the close status.
Thanks @jjconti for reporting and make this info available for IRuby users.
