### ISSUE TITLE
issues on Windows

### ISSUE THREAD

**Issue by mwiebe** [damianavila/live_reveal#44]
Giving this a shot on Windows, but ran into a few issues. The rise profile didn't seem to have the live_reveal stuff in it, but that seems to be in the default profile. The notebook is written calling out to the posix shell. I patched it to use shutil, but it was still erroring. Here's the diff from the essential that notebook:

```
      "input": [
-      "import os\n",
+      "import os, shutil\n",
       "import IPython.html.nbextensions as nbext\n",
       "\n",
       "# download rise extension\n",
@@ -42,21 +42,58 @@
       "nbext_folder = os.path.join(nbext.get_ipython_dir(), \"nbextensions\")\n
       "install_folder = os.path.join(nbext_folder, nbext_name + \"-\" + version
       "rise_folder =  os.path.join(install_folder, \"livereveal\")\n",
-      "!mv {rise_folder} {nbext_folder}\n",
+      "shutil.move(rise_folder, nbext_folder)\n",
       "\n",
       "# create a rise profile and add the proper custom.js\n",
       "!ipython profile create rise\n",
       "custom_js = os.path.join(nbext_folder, nbext_name + \"-\" + version, \"c
       "tgt = os.path.join(nbext.get_ipython_dir(), 'profile_rise', 'static', 'c
-      "!mv {custom_js} {tgt}\n",
+      "shutil.move(custom_js, tgt)\n",
       "\n",
       "# clean the mess\n",
-      "!rm -r {install_folder}"
+      "shutil.rmtree(install_folder)"
```

**Comment by franktoffel** [comment]
I successfully installed it on windows few months ago.
What I did was to replace the bash commands by the windows cmd.exe one.

I am a newbie but this helped me:
https://github.com/mikecroucher/Windows_Scientific_Computing/blob/master/Powershell.md

I didn't know about shutil, though. It will be neat (when fixed)!

**Comment by damianavila** [comment]
We need a real multi-platform installation, closing here in favour of #52
