### ISSUE TITLE
display error on latest ipython master

### ISSUE THREAD

**Issue by mwiebe** [damianavila/live_reveal#46]
Tried live_reveal against the latest ipython master, and the reveal slides get rendered into a tiny sliver instead of the full browser window. Reverting ipython to a commit from a few days back fixed it for me.

**Comment by twiecki** [comment]
Just ran into this same issue with most recent Jupyter.

**Comment by damianavila** [comment]
Going to investigate today... I wanted a more "quiet" master before fixing it ;-)

**Comment by twiecki** [comment]
Good luck! :)

**Comment by twiecki** [comment]
@damianavila sorry to be dense, but is there any progress? I need my live reveal! ;)

**Comment by damianavila** [comment]
Sorry... I was busy with the Bokeh release... attacking this one tonight, I promise :-)
