### ISSUE TITLE
Interactive widgets are messed up in the presentation  mode

### ISSUE THREAD

**Issue by eco32i** [damianavila/live_reveal#47]
![screenshot from 2015-01-11 22 02 34](https://cloud.githubusercontent.com/assets/4699600/5698524/b7b19e04-99dd-11e4-8fd0-d56a56aa8ce1.png)

Clicking on the widget controls sends me to the first slide. 

The same widget works fine in the notebook. 
IPython version 2.3.1

**Comment by damianavila** [comment]
Can you post an example notebook to reproduce? Because I tried some other widgets and they was working OK. Thanks!

**Comment by eco32i** [comment]
Here is an example: https://gist.github.com/eco32i/0c3dcffb9b8d0e2db766
Everything's fine in notebook but as soon as I go to the presentation mode (Alt-R) the DropdownWidget becomes messed up.

**Comment by damianavila** [comment]
Just an update, I will explore this issue this week, sorry for the delay...

**Comment by takluyver** [comment]
I also saw this. It seems to be the styling of DropdownWidget in particular that goes wrong.

**Comment by damianavila** [comment]
Yes, I saw this in the past, probably related with reveal css... I will investigate.

**Comment by damianavila** [comment]
OK, #69 should fix the issue... at least in my tests, please reopen if it is not the case... thanks for the report.
