### ISSUE TITLE
note cells stay hidden after leaving presentation mode

### ISSUE THREAD

**Issue by takluyver** [damianavila/live_reveal#58]
If I set some cells as notes using the cell toolbar, they are hidden when I switch into presentation mode (presumably usable with a speaker view), but they don't come back when I leave presentation mode. Refreshing the page restores them.

**Comment by takluyver** [comment]
Also, and possibly related, cells marked 'skip' seem to come back at the top of the file regardless of where they were before.

**Comment by takluyver** [comment]
OK, the problem with skipped cells is something I've introduced in the PR I just opened. The problem with note cells is in master, however.

**Comment by damianavila** [comment]
OK, I will take a look at the PR...
