### ISSUE TITLE
Problem get it running ...

### ISSUE THREAD

**Issue by bulli92** [damianavila/live_reveal#62]
Hi,

I'd love to use the dynamic ipython slideshow for my teaching.
I am therefore trying to get RJSE/RISE running in my ipython notebook (v2.4). I have however trouble with the installation. I tried two different approaches:

a) cloning the current repo and then running `python setup.py install`
--> to my underanding, this installs directly in the `ǹbextensions` folder

b) running the script `Install_RJSE.ipynb`
--> which downloads the tagged 2.x version and generates a profile.

However, in both cases I have trouble getting the slideshow running. The button to activate the slideshow is available. When I press it, I however get NO presentation. Instead, the ipython notebook pager page opens at the bottom of the notebook (this is where typically the help/documentation is shown). However, the pager page is empty. What also happens is that the toolbars disappear. I attach two screenshots to illustrate this behavior.

*BEFORE ACTIVATION*
![screenshot from 2015-02-13 11 34 16](https://cloud.githubusercontent.com/assets/2847755/6186059/30f2335e-b375-11e4-96cd-147498de35f5.png)

*AND AFTER ...*
![after](https://cloud.githubusercontent.com/assets/2847755/6186079/55191ffe-b375-11e4-9e14-3d99f4ef6ab3.png)
Note the white and empty pager frame at the bottom!

When starting the notebook with the `--debug` option, I can also find no obvious problem. The strange thing is that I tried the installation this morning once and it was running. Then I was leaving the slidemode using the shortcut given in the help. Since then it did not work any more. I remove everything related to `live_reveal` in the `.ipython` directory and tried to reinstall using the two different methods indicated above.

Any idea how to fix the issue or identify where it is coming from?

**Comment by damianavila** [comment]
I have not tested the extension with 2.4.1 yet... maybe some change is need... there is currently a PR that's seems to make it work #57, but I have to check it yet... I will test this during the weekend and I will let you know...

**Comment by bulli92** [comment]
o.k., great, thanks for the fast reply. With which ipython versions did you work so far

**Comment by damianavila** [comment]
Please, test master with the first installation option... not master is compatible with 2.4.1 too.

**Comment by bulli92** [comment]
great, seems to work for me now!
